/**
 * サンプル案件: IT大企業「テクノフューチャー株式会社」の組織図
 *
 * 5階層・約30名の一般的なIT系大企業組織
 *
 * 代表取締役社長: 山田太郎
 * ├─ 執行役員CTO 佐藤健一 → テクノロジー本部
 * │   ├─ 開発部: 中村隆志(部長), 渡辺美咲(次長)
 * │   │   ├─ プロダクト開発課: 小林翔太(課長), 加藤恵(主任), 吉田裕也(エンジニア)
 * │   │   └─ インフラ課: 松本大輝(課長), 藤田理恵(主任)
 * │   └─ AI推進室: 井上智子(室長), 坂本陸(リサーチャー)
 * ├─ 執行役員CFO 高橋直美 → コーポレート本部
 * │   ├─ 経営企画部: 田中誠(部長), 山口千佳(課長)
 * │   ├─ 人事部: 伊藤雅人(部長), 西村沙也加(課長), 岡田凛(主任)
 * │   └─ 法務部: 上田正義(部長), 前田萌(リーガルカウンセル)
 * └─ 執行役員CSO 鈴木浩二 → ビジネス本部
 *     ├─ 営業部: 木村洋介(部長), 林真理子(次長)
 *     │   ├─ エンタープライズ営業課: 清水拓也(課長), 森下愛(主任), 石井遼(担当)
 *     │   └─ SMB営業課: 原口大地(課長), 中島彩(主任)
 *     └─ マーケティング部: 池田恵美(部長), 川口翔(マネージャー)
 */
import type { Stakeholder } from "@/types/stakeholder";
import type { Deal } from "@/types/deal";
import type { OrgGroup } from "@/types/org-group";
import type { Relationship } from "@/types/relationship";

export const SAMPLE_DEAL_ID = "sample-deal-001";

export const SAMPLE_DEAL: Deal = {
  id: SAMPLE_DEAL_ID,
  name: "[サンプル] デモ株式会社",
  clientName: "デモ株式会社",
  stage: "proposal",
  description: "IT大企業の組織図サンプル。5階層・約30名の一般的な組織構造を再現しています。部署のドラッグ&ドロップ、関係線、態度の色分けなどの機能をお試しいただけます。",
  targetAmount: 120000000,
  expectedCloseDate: "2026-12-31",
  createdAt: "2026-03-01T09:00:00.000Z",
  updatedAt: "2026-03-04T09:00:00.000Z",
};

const ts = "2026-03-01T09:00:00.000Z";

// ========================================
// OrgGroups
// ========================================
export const SAMPLE_ORG_GROUPS: OrgGroup[] = [
  // ── テクノロジー本部 ──
  {
    id: "sg-tech",
    dealId: SAMPLE_DEAL_ID,
    name: "テクノロジー本部",
    parentGroupId: null,
    sortOrder: 0,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sg-dev",
    dealId: SAMPLE_DEAL_ID,
    name: "開発部",
    parentGroupId: "sg-tech",
    sortOrder: 0,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sg-product-dev",
    dealId: SAMPLE_DEAL_ID,
    name: "プロダクト開発課",
    parentGroupId: "sg-dev",
    sortOrder: 0,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sg-infra",
    dealId: SAMPLE_DEAL_ID,
    name: "インフラ課",
    parentGroupId: "sg-dev",
    sortOrder: 1,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sg-ai",
    dealId: SAMPLE_DEAL_ID,
    name: "AI推進室",
    parentGroupId: "sg-tech",
    sortOrder: 1,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── コーポレート本部 ──
  {
    id: "sg-corp",
    dealId: SAMPLE_DEAL_ID,
    name: "コーポレート本部",
    parentGroupId: null,
    sortOrder: 1,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sg-planning",
    dealId: SAMPLE_DEAL_ID,
    name: "経営企画部",
    parentGroupId: "sg-corp",
    sortOrder: 0,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sg-hr",
    dealId: SAMPLE_DEAL_ID,
    name: "人事部",
    parentGroupId: "sg-corp",
    sortOrder: 1,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sg-legal",
    dealId: SAMPLE_DEAL_ID,
    name: "法務部",
    parentGroupId: "sg-corp",
    sortOrder: 2,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── ビジネス本部 ──
  {
    id: "sg-biz",
    dealId: SAMPLE_DEAL_ID,
    name: "ビジネス本部",
    parentGroupId: null,
    sortOrder: 2,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sg-sales",
    dealId: SAMPLE_DEAL_ID,
    name: "営業部",
    parentGroupId: "sg-biz",
    sortOrder: 0,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sg-enterprise",
    dealId: SAMPLE_DEAL_ID,
    name: "エンタープライズ営業課",
    parentGroupId: "sg-sales",
    sortOrder: 0,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sg-smb",
    dealId: SAMPLE_DEAL_ID,
    name: "SMB営業課",
    parentGroupId: "sg-sales",
    sortOrder: 1,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sg-marketing",
    dealId: SAMPLE_DEAL_ID,
    name: "マーケティング部",
    parentGroupId: "sg-biz",
    sortOrder: 1,
    createdAt: ts,
    updatedAt: ts,
  },
];

// ========================================
// Stakeholders (30名)
// ========================================
export const SAMPLE_STAKEHOLDERS: Stakeholder[] = [
  // ── 経営トップ（フリーフローティング） ──
  {
    id: "ss-001",
    dealId: SAMPLE_DEAL_ID,
    name: "山田 太郎",
    department: "経営",
    title: "代表取締役社長",
    roleInDeal: "decision_maker",
    influenceLevel: 5,
    attitude: "promoter",
    mission: "会社全体の経営方針決定",
    relationshipOwner: "赤坂",
    parentId: null,
    email: "yamada@technofuture.co.jp",
    phone: "03-6000-0001",
    notes: "DX推進を経営の最重要テーマとして掲げる。決裁者",
    groupId: null,
    orgLevel: 1,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── 執行役員（フリーフローティング） ──
  {
    id: "ss-002",
    dealId: SAMPLE_DEAL_ID,
    name: "佐藤 健一",
    department: "テクノロジー本部",
    title: "執行役員 CTO",
    roleInDeal: "approver",
    influenceLevel: 5,
    attitude: "promoter",
    mission: "技術戦略の立案・実行",
    relationshipOwner: "赤坂",
    parentId: "ss-001",
    email: "sato@technofuture.co.jp",
    phone: "03-6000-0002",
    notes: "最新技術への投資に積極的。AI・クラウドの導入を推進",
    groupId: null,
    orgLevel: 1,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-003",
    dealId: SAMPLE_DEAL_ID,
    name: "高橋 直美",
    department: "コーポレート本部",
    title: "執行役員 CFO",
    roleInDeal: "gatekeeper",
    influenceLevel: 5,
    attitude: "cautious",
    mission: "財務統制・投資判断",
    relationshipOwner: "",
    parentId: "ss-001",
    email: "takahashi@technofuture.co.jp",
    phone: "03-6000-0003",
    notes: "ROIを厳密に評価。コスト削減効果が見えないと承認しない",
    groupId: null,
    orgLevel: 1,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-004",
    dealId: SAMPLE_DEAL_ID,
    name: "鈴木 浩二",
    department: "ビジネス本部",
    title: "執行役員 CSO",
    roleInDeal: "approver",
    influenceLevel: 5,
    attitude: "supportive",
    mission: "売上・事業拡大の統括",
    relationshipOwner: "赤坂",
    parentId: "ss-001",
    email: "suzuki@technofuture.co.jp",
    phone: "03-6000-0004",
    notes: "営業現場の効率化ツールに関心が高い。パートナー連携に前向き",
    groupId: null,
    orgLevel: 1,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── テクノロジー本部 > 開発部 ──
  {
    id: "ss-005",
    dealId: SAMPLE_DEAL_ID,
    name: "中村 隆志",
    department: "開発部",
    title: "部長",
    roleInDeal: "evaluator",
    influenceLevel: 4,
    attitude: "supportive",
    mission: "プロダクト開発の品質管理・リソース配分",
    relationshipOwner: "",
    parentId: "ss-002",
    email: "nakamura@technofuture.co.jp",
    phone: "03-6000-1001",
    notes: "技術選定の最終判断者。アーキテクチャに強いこだわり",
    groupId: "sg-dev",
    orgLevel: 2,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-006",
    dealId: SAMPLE_DEAL_ID,
    name: "渡辺 美咲",
    department: "開発部",
    title: "次長",
    roleInDeal: "evaluator",
    influenceLevel: 3,
    attitude: "neutral",
    mission: "開発プロセスの最適化",
    relationshipOwner: "",
    parentId: "ss-005",
    email: "watanabe@technofuture.co.jp",
    phone: "",
    notes: "アジャイル推進担当。ツール導入に中立的だが合理性があれば賛同",
    groupId: "sg-dev",
    orgLevel: 3,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── テクノロジー本部 > 開発部 > プロダクト開発課 ──
  {
    id: "ss-007",
    dealId: SAMPLE_DEAL_ID,
    name: "小林 翔太",
    department: "プロダクト開発課",
    title: "課長",
    roleInDeal: "initiator",
    influenceLevel: 3,
    attitude: "promoter",
    mission: "新機能開発のリード",
    relationshipOwner: "",
    parentId: "ss-006",
    email: "kobayashi@technofuture.co.jp",
    phone: "",
    notes: "導入推進のキーパーソン。技術的な検証を自ら行う",
    groupId: "sg-product-dev",
    orgLevel: 4,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-008",
    dealId: SAMPLE_DEAL_ID,
    name: "加藤 恵",
    department: "プロダクト開発課",
    title: "主任",
    roleInDeal: "user",
    influenceLevel: 2,
    attitude: "supportive",
    mission: "フロントエンド開発",
    relationshipOwner: "",
    parentId: "ss-007",
    email: "kato@technofuture.co.jp",
    phone: "",
    notes: "UIに詳しい。ユーザビリティ評価を担当",
    groupId: "sg-product-dev",
    orgLevel: 5,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-009",
    dealId: SAMPLE_DEAL_ID,
    name: "吉田 裕也",
    department: "プロダクト開発課",
    title: "エンジニア",
    roleInDeal: "user",
    influenceLevel: 1,
    attitude: "neutral",
    mission: "バックエンド開発",
    relationshipOwner: "",
    parentId: "ss-007",
    email: "yoshida@technofuture.co.jp",
    phone: "",
    notes: "API設計・バックエンド実装担当",
    groupId: "sg-product-dev",
    orgLevel: 5,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── テクノロジー本部 > 開発部 > インフラ課 ──
  {
    id: "ss-010",
    dealId: SAMPLE_DEAL_ID,
    name: "松本 大輝",
    department: "インフラ課",
    title: "課長",
    roleInDeal: "evaluator",
    influenceLevel: 3,
    attitude: "cautious",
    mission: "インフラ設計・運用管理",
    relationshipOwner: "",
    parentId: "ss-006",
    email: "matsumoto@technofuture.co.jp",
    phone: "",
    notes: "セキュリティ基準に厳しい。SaaS導入にはセキュリティレビューを要求",
    groupId: "sg-infra",
    orgLevel: 4,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-011",
    dealId: SAMPLE_DEAL_ID,
    name: "藤田 理恵",
    department: "インフラ課",
    title: "主任",
    roleInDeal: "user",
    influenceLevel: 2,
    attitude: "neutral",
    mission: "クラウドインフラの運用",
    relationshipOwner: "",
    parentId: "ss-010",
    email: "fujita@technofuture.co.jp",
    phone: "",
    notes: "AWS/GCP運用のスペシャリスト",
    groupId: "sg-infra",
    orgLevel: 5,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── テクノロジー本部 > AI推進室 ──
  {
    id: "ss-012",
    dealId: SAMPLE_DEAL_ID,
    name: "井上 智子",
    department: "AI推進室",
    title: "室長",
    roleInDeal: "initiator",
    influenceLevel: 4,
    attitude: "promoter",
    mission: "AI活用戦略の立案・推進",
    relationshipOwner: "",
    parentId: "ss-002",
    email: "inoue@technofuture.co.jp",
    phone: "03-6000-1010",
    notes: "LLM・生成AI活用の第一人者。新ツール導入に非常に積極的",
    groupId: "sg-ai",
    orgLevel: 3,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-013",
    dealId: SAMPLE_DEAL_ID,
    name: "坂本 陸",
    department: "AI推進室",
    title: "リサーチャー",
    roleInDeal: "user",
    influenceLevel: 2,
    attitude: "promoter",
    mission: "AI技術のリサーチ・PoC実施",
    relationshipOwner: "",
    parentId: "ss-012",
    email: "sakamoto@technofuture.co.jp",
    phone: "",
    notes: "技術検証を担当。PoCの実施・レポート作成が早い",
    groupId: "sg-ai",
    orgLevel: 5,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── コーポレート本部 > 経営企画部 ──
  {
    id: "ss-014",
    dealId: SAMPLE_DEAL_ID,
    name: "田中 誠",
    department: "経営企画部",
    title: "部長",
    roleInDeal: "gatekeeper",
    influenceLevel: 4,
    attitude: "neutral",
    mission: "中期経営計画・投資管理",
    relationshipOwner: "",
    parentId: "ss-003",
    email: "tanaka@technofuture.co.jp",
    phone: "03-6000-2001",
    notes: "投資判断の実務リーダー。数字に基づいた判断を重視",
    groupId: "sg-planning",
    orgLevel: 2,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-015",
    dealId: SAMPLE_DEAL_ID,
    name: "山口 千佳",
    department: "経営企画部",
    title: "課長",
    roleInDeal: "evaluator",
    influenceLevel: 3,
    attitude: "neutral",
    mission: "事業計画のレビュー・分析",
    relationshipOwner: "",
    parentId: "ss-014",
    email: "yamaguchi@technofuture.co.jp",
    phone: "",
    notes: "Excel/スプレッドシートでの分析が得意。定量評価を担当",
    groupId: "sg-planning",
    orgLevel: 4,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── コーポレート本部 > 人事部 ──
  {
    id: "ss-016",
    dealId: SAMPLE_DEAL_ID,
    name: "伊藤 雅人",
    department: "人事部",
    title: "部長",
    roleInDeal: "user",
    influenceLevel: 3,
    attitude: "supportive",
    mission: "人材戦略・組織開発",
    relationshipOwner: "",
    parentId: "ss-003",
    email: "ito@technofuture.co.jp",
    phone: "03-6000-2010",
    notes: "組織可視化ツールに関心あり。タレントマネジメントとの連携を期待",
    groupId: "sg-hr",
    orgLevel: 2,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-017",
    dealId: SAMPLE_DEAL_ID,
    name: "西村 沙也加",
    department: "人事部",
    title: "課長",
    roleInDeal: "user",
    influenceLevel: 2,
    attitude: "supportive",
    mission: "採用・教育研修",
    relationshipOwner: "",
    parentId: "ss-016",
    email: "nishimura@technofuture.co.jp",
    phone: "",
    notes: "組織図データの活用で採用プロセス改善を検討中",
    groupId: "sg-hr",
    orgLevel: 4,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-018",
    dealId: SAMPLE_DEAL_ID,
    name: "岡田 凛",
    department: "人事部",
    title: "主任",
    roleInDeal: "user",
    influenceLevel: 1,
    attitude: "neutral",
    mission: "採用事務・研修運営",
    relationshipOwner: "",
    parentId: "ss-017",
    email: "okada@technofuture.co.jp",
    phone: "",
    notes: "日常的にHRツールを利用。使い勝手のフィードバックが期待できる",
    groupId: "sg-hr",
    orgLevel: 5,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── コーポレート本部 > 法務部 ──
  {
    id: "ss-019",
    dealId: SAMPLE_DEAL_ID,
    name: "上田 正義",
    department: "法務部",
    title: "部長",
    roleInDeal: "gatekeeper",
    influenceLevel: 4,
    attitude: "opposed",
    mission: "契約審査・コンプライアンス管理",
    relationshipOwner: "",
    parentId: "ss-003",
    email: "ueda@technofuture.co.jp",
    phone: "03-6000-2020",
    notes: "外部SaaS利用の規約チェックが厳しい。個人情報保護に敏感",
    groupId: "sg-legal",
    orgLevel: 2,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-020",
    dealId: SAMPLE_DEAL_ID,
    name: "前田 萌",
    department: "法務部",
    title: "リーガルカウンセル",
    roleInDeal: "evaluator",
    influenceLevel: 3,
    attitude: "cautious",
    mission: "契約書レビュー・法的リスク評価",
    relationshipOwner: "",
    parentId: "ss-019",
    email: "maeda@technofuture.co.jp",
    phone: "",
    notes: "SaaS利用規約の詳細レビューを担当。データ所在地に関する質問が多い",
    groupId: "sg-legal",
    orgLevel: 4,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── ビジネス本部 > 営業部 ──
  {
    id: "ss-021",
    dealId: SAMPLE_DEAL_ID,
    name: "木村 洋介",
    department: "営業部",
    title: "部長",
    roleInDeal: "approver",
    influenceLevel: 4,
    attitude: "promoter",
    mission: "営業戦略の立案・実行",
    relationshipOwner: "赤坂",
    parentId: "ss-004",
    email: "kimura@technofuture.co.jp",
    phone: "03-6000-3001",
    notes: "営業効率化に強い関心。ツール導入で成約率向上を目指す",
    groupId: "sg-sales",
    orgLevel: 2,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-022",
    dealId: SAMPLE_DEAL_ID,
    name: "林 真理子",
    department: "営業部",
    title: "次長",
    roleInDeal: "evaluator",
    influenceLevel: 3,
    attitude: "supportive",
    mission: "営業チームのマネジメント",
    relationshipOwner: "",
    parentId: "ss-021",
    email: "hayashi@technofuture.co.jp",
    phone: "",
    notes: "現場との橋渡し役。ツール定着の鍵を握る人物",
    groupId: "sg-sales",
    orgLevel: 3,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── ビジネス本部 > 営業部 > エンタープライズ営業課 ──
  {
    id: "ss-023",
    dealId: SAMPLE_DEAL_ID,
    name: "清水 拓也",
    department: "エンタープライズ営業課",
    title: "課長",
    roleInDeal: "user",
    influenceLevel: 3,
    attitude: "supportive",
    mission: "大手企業向け営業の統括",
    relationshipOwner: "",
    parentId: "ss-022",
    email: "shimizu@technofuture.co.jp",
    phone: "",
    notes: "大手SIer・金融機関を担当。組織図把握のニーズが最も高い",
    groupId: "sg-enterprise",
    orgLevel: 4,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-024",
    dealId: SAMPLE_DEAL_ID,
    name: "森下 愛",
    department: "エンタープライズ営業課",
    title: "主任",
    roleInDeal: "user",
    influenceLevel: 2,
    attitude: "promoter",
    mission: "エンタープライズ顧客のアカウント管理",
    relationshipOwner: "",
    parentId: "ss-023",
    email: "morishita@technofuture.co.jp",
    phone: "",
    notes: "現在Excelで組織図を管理中。ツール化を強く希望",
    groupId: "sg-enterprise",
    orgLevel: 5,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-025",
    dealId: SAMPLE_DEAL_ID,
    name: "石井 遼",
    department: "エンタープライズ営業課",
    title: "担当",
    roleInDeal: "user",
    influenceLevel: 1,
    attitude: "neutral",
    mission: "新規顧客開拓",
    relationshipOwner: "",
    parentId: "ss-023",
    email: "ishii@technofuture.co.jp",
    phone: "",
    notes: "入社2年目。顧客組織の理解に苦労しており可視化ツールに興味",
    groupId: "sg-enterprise",
    orgLevel: 5,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── ビジネス本部 > 営業部 > SMB営業課 ──
  {
    id: "ss-026",
    dealId: SAMPLE_DEAL_ID,
    name: "原口 大地",
    department: "SMB営業課",
    title: "課長",
    roleInDeal: "user",
    influenceLevel: 3,
    attitude: "neutral",
    mission: "中小企業向け営業の統括",
    relationshipOwner: "",
    parentId: "ss-022",
    email: "haraguchi@technofuture.co.jp",
    phone: "",
    notes: "SMBはスピード重視。ツールのシンプルさを求める",
    groupId: "sg-smb",
    orgLevel: 4,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-027",
    dealId: SAMPLE_DEAL_ID,
    name: "中島 彩",
    department: "SMB営業課",
    title: "主任",
    roleInDeal: "user",
    influenceLevel: 2,
    attitude: "supportive",
    mission: "中小企業のアカウント管理",
    relationshipOwner: "",
    parentId: "ss-026",
    email: "nakajima@technofuture.co.jp",
    phone: "",
    notes: "既存のCRMツールとの連携を期待。データ入力の手間を減らしたい",
    groupId: "sg-smb",
    orgLevel: 5,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── ビジネス本部 > マーケティング部 ──
  {
    id: "ss-028",
    dealId: SAMPLE_DEAL_ID,
    name: "池田 恵美",
    department: "マーケティング部",
    title: "部長",
    roleInDeal: "user",
    influenceLevel: 3,
    attitude: "supportive",
    mission: "マーケティング戦略・ブランド管理",
    relationshipOwner: "",
    parentId: "ss-004",
    email: "ikeda@technofuture.co.jp",
    phone: "03-6000-3020",
    notes: "顧客インサイトの可視化に関心。ABMとの連携を検討中",
    groupId: "sg-marketing",
    orgLevel: 2,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "ss-029",
    dealId: SAMPLE_DEAL_ID,
    name: "川口 翔",
    department: "マーケティング部",
    title: "マネージャー",
    roleInDeal: "user",
    influenceLevel: 2,
    attitude: "neutral",
    mission: "デジタルマーケティング・リード獲得",
    relationshipOwner: "",
    parentId: "ss-028",
    email: "kawaguchi@technofuture.co.jp",
    phone: "",
    notes: "MA/CRMツールに精通。データ連携の技術面を理解している",
    groupId: "sg-marketing",
    orgLevel: 4,
    createdAt: ts,
    updatedAt: ts,
  },
];

// ========================================
// Relationships（関係線）
// ========================================
export const SAMPLE_RELATIONSHIPS: Relationship[] = [
  // CTO ↔ CSO: 技術×営業の連携
  {
    id: "sr-001",
    dealId: SAMPLE_DEAL_ID,
    sourceId: "ss-002",
    targetId: "ss-004",
    type: "alliance",
    label: "プロダクト戦略で密に連携",
    bidirectional: true,
    createdAt: ts,
  },
  // CFO ↔ 法務部長: 慎重派の連携
  {
    id: "sr-002",
    dealId: SAMPLE_DEAL_ID,
    sourceId: "ss-003",
    targetId: "ss-019",
    type: "alliance",
    label: "リスク管理で連携",
    bidirectional: true,
    createdAt: ts,
  },
  // CTO → CFO: スピード vs コスト
  {
    id: "sr-003",
    dealId: SAMPLE_DEAL_ID,
    sourceId: "ss-002",
    targetId: "ss-003",
    type: "rivalry",
    label: "投資スピードで意見対立",
    bidirectional: true,
    createdAt: ts,
  },
  // AI推進室長 → プロダクト開発課長: 技術連携
  {
    id: "sr-004",
    dealId: SAMPLE_DEAL_ID,
    sourceId: "ss-012",
    targetId: "ss-007",
    type: "influence",
    label: "AI機能のプロダクト統合を推進",
    bidirectional: false,
    createdAt: ts,
  },
  // 営業部長 → 経営企画部長: 予算確保の働きかけ
  {
    id: "sr-005",
    dealId: SAMPLE_DEAL_ID,
    sourceId: "ss-021",
    targetId: "ss-014",
    type: "influence",
    label: "営業ツール予算の確保を要請",
    bidirectional: false,
    createdAt: ts,
  },
  // エンプラ営業課長 ↔ マーケ部長: ABM連携
  {
    id: "sr-006",
    dealId: SAMPLE_DEAL_ID,
    sourceId: "ss-023",
    targetId: "ss-028",
    type: "alliance",
    label: "ABM施策で協業",
    bidirectional: true,
    createdAt: ts,
  },
  // インフラ課長 → 法務部長: セキュリティ審査の協力
  {
    id: "sr-007",
    dealId: SAMPLE_DEAL_ID,
    sourceId: "ss-010",
    targetId: "ss-019",
    type: "informal",
    label: "SaaS導入のセキュリティ審査で連携",
    bidirectional: false,
    createdAt: ts,
  },
];
